---
- name: Remove local OpenShift cluster VM shells
  hosts: hypervisors
  become: true
  gather_facts: false
  vars_files:
    - ../../vars/cluster/openshift_install_cluster.yml
    - ../../vars/guests/openshift_cluster_vm.yml
  roles:
    - openshift_cluster_cleanup

