#!/usr/bin/python3
"""
Persistent Calabi Observer exporter daemon.

The exporter owns collection cadence, keeps the latest successful sample in
memory, writes the Cockpit JSON snapshot, and serves cached Prometheus metrics.
HTTP scrapes never trigger collection.
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import socket
import sys
import tempfile
import threading
import time
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any

import collector
import prometheus_exporter


SNAPSHOT_PATH = "/run/calabi-observer/metrics.json"
CONFIG_PATH = "/etc/calabi-observer/prometheus.json"
DEFAULT_LISTEN_ADDRESS = "127.0.0.1:9910"
DEFAULT_INTERVAL_SECONDS = 5
FULL_INTERVAL_SECONDS = 60
FULL_ONLY_KEYS = [
    "cpu_pools",
    "cpu_pool_map",
    "domains",
    "domain_cgroups",
    "domain_ksm",
    "domain_swap",
    "tier_totals",
    "guest_memory_bytes",
    "guest_vcpus",
]


class ExporterState:
    def __init__(self) -> None:
        self.lock = threading.Lock()
        self.latest_payload: dict[str, Any] | None = None
        self.metrics_body = self._fallback_metrics()
        self.last_success = 0.0
        self.last_attempt = 0.0
        self.last_error = ""
        self.collect_error = False

    def _fallback_metrics(self) -> str:
        return "\n".join([
            "# Generated by calabi-exporter",
            "# HELP calabi_observer_up Whether the Calabi Observer exporter has a successful cached sample.",
            "# TYPE calabi_observer_up gauge",
            "calabi_observer_up 0",
            "# HELP calabi_observer_collect_error Whether the last Calabi Observer collection failed.",
            "# TYPE calabi_observer_collect_error gauge",
            "calabi_observer_collect_error 1",
            "# HELP calabi_observer_last_success_timestamp_seconds Unix timestamp of the last successful collection.",
            "# TYPE calabi_observer_last_success_timestamp_seconds gauge",
            "calabi_observer_last_success_timestamp_seconds 0",
            "",
        ])

    def update_success(self, payload: dict[str, Any]) -> None:
        now = time.time()
        metrics = append_exporter_metrics(
            prometheus_exporter.format_metrics(payload),
            collect_error=False,
            last_success=now,
        )
        with self.lock:
            self.latest_payload = payload
            self.metrics_body = metrics
            self.last_success = now
            self.last_attempt = now
            self.last_error = ""
            self.collect_error = False

    def update_failure(self, exc: Exception) -> None:
        now = time.time()
        with self.lock:
            self.last_attempt = now
            self.last_error = str(exc)
            self.collect_error = True
            if self.latest_payload is None:
                self.metrics_body = self._fallback_metrics()
            else:
                self.metrics_body = append_exporter_metrics(
                    prometheus_exporter.format_metrics(self.latest_payload),
                    collect_error=True,
                    last_success=self.last_success,
                )

    def snapshot(self) -> dict[str, Any]:
        with self.lock:
            return {
                "has_sample": self.latest_payload is not None,
                "payload": self.latest_payload,
                "metrics_body": self.metrics_body,
                "last_success": self.last_success,
                "last_attempt": self.last_attempt,
                "last_error": self.last_error,
                "collect_error": self.collect_error,
            }


COLLECTOR_CACHE = collector.CollectorCache()


def append_exporter_metrics(metrics: str, collect_error: bool, last_success: float) -> str:
    extra = [
        "# HELP calabi_observer_collect_error Whether the last Calabi Observer collection failed.",
        "# TYPE calabi_observer_collect_error gauge",
        f"calabi_observer_collect_error {1 if collect_error else 0}",
        "# HELP calabi_observer_last_success_timestamp_seconds Unix timestamp of the last successful collection.",
        "# TYPE calabi_observer_last_success_timestamp_seconds gauge",
        f"calabi_observer_last_success_timestamp_seconds {last_success:.3f}",
    ]
    return metrics.rstrip() + "\n" + "\n".join(extra) + "\n"


def parse_listen_address(value: str) -> tuple[str, int]:
    value = value.strip()
    if value.startswith("["):
        host, sep, tail = value[1:].partition("]:")
        if not sep:
            raise ValueError("IPv6 listen addresses must use [addr]:port syntax.")
        port_text = tail
    else:
        host, sep, port_text = value.rpartition(":")
        if not sep:
            raise ValueError("Listen address must include a port, for example 127.0.0.1:9910.")
    if not port_text.isdigit():
        raise ValueError("Listen port must be numeric.")
    port = int(port_text)
    if port < 1 or port > 65535:
        raise ValueError("Listen port must be between 1 and 65535.")
    return host, port


def normalize_interval(value: Any) -> int:
    try:
        interval = int(value)
    except (TypeError, ValueError):
        interval = DEFAULT_INTERVAL_SECONDS
    return max(2, min(interval, 3600))


def read_config() -> dict[str, Any]:
    cfg: dict[str, Any] = {
        "interval_seconds": DEFAULT_INTERVAL_SECONDS,
        "listen_address": DEFAULT_LISTEN_ADDRESS,
    }
    try:
        with open(CONFIG_PATH, encoding="utf-8") as handle:
            raw = json.load(handle)
        if isinstance(raw, dict):
            cfg.update(raw)
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        pass
    cfg["interval_seconds"] = normalize_interval(cfg.get("interval_seconds"))
    cfg["listen_address"] = str(cfg.get("listen_address") or DEFAULT_LISTEN_ADDRESS).strip()
    parse_listen_address(cfg["listen_address"])
    return cfg


def write_atomic(path: str, content: str, mode: int = 0o644) -> None:
    directory = os.path.dirname(path)
    os.makedirs(directory, mode=0o755, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=f".{os.path.basename(path)}.", dir=directory, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(tmp_path, mode)
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except FileNotFoundError:
            pass
        raise


def merge_cached_fast_payload(payload: dict[str, Any], cached: dict[str, Any]) -> None:
    for key in FULL_ONLY_KEYS:
        if key in cached and key not in payload:
            payload[key] = cached[key]


def collect_payload(full: bool, cached_full: dict[str, Any]) -> dict[str, Any]:
    payload = collector.collect(fast=not full, cache=COLLECTOR_CACHE)
    if full:
        cached_full.clear()
        cached_full.update({key: payload[key] for key in FULL_ONLY_KEYS if key in payload})
    else:
        merge_cached_fast_payload(payload, cached_full)
    return payload


def publish_snapshot(payload: dict[str, Any]) -> None:
    write_atomic(SNAPSHOT_PATH, json.dumps(payload, sort_keys=True) + "\n")


def collect_once(full: bool, cached_full: dict[str, Any], state: ExporterState) -> None:
    payload = collect_payload(full=full, cached_full=cached_full)
    publish_snapshot(payload)
    state.update_success(payload)


def collection_loop(state: ExporterState, stop_event: threading.Event) -> None:
    cached_full: dict[str, Any] = {}
    last_full = 0.0
    next_collect = 0.0

    while not stop_event.is_set():
        now = time.monotonic()
        if now < next_collect:
            stop_event.wait(min(next_collect - now, 1.0))
            continue

        try:
            interval = read_config()["interval_seconds"]
        except Exception as exc:
            interval = DEFAULT_INTERVAL_SECONDS
            state.update_failure(exc)
            sys.stderr.write(f"calabi exporter config read failed: {exc}\n")
            sys.stderr.flush()

        full = not cached_full or (now - last_full) >= FULL_INTERVAL_SECONDS
        try:
            collect_once(full=full, cached_full=cached_full, state=state)
            if full:
                last_full = now
        except Exception as exc:
            state.update_failure(exc)
            sys.stderr.write(f"calabi exporter collection failed: {exc}\n")
            sys.stderr.flush()

        next_collect = time.monotonic() + interval


class CalabiHandler(BaseHTTPRequestHandler):
    server_version = "calabi-exporter/1"

    def do_GET(self) -> None:
        state: ExporterState = self.server.exporter_state  # type: ignore[attr-defined]
        snap = state.snapshot()

        if self.path == "/metrics":
            self._send_bytes(HTTPStatus.OK, "text/plain; version=0.0.4; charset=utf-8", snap["metrics_body"].encode("utf-8"))
            return

        if self.path == "/healthz":
            healthy = bool(snap["has_sample"]) and not snap["collect_error"]
            body = json.dumps({
                "ok": healthy,
                "has_sample": snap["has_sample"],
                "collect_error": snap["collect_error"],
                "last_success": snap["last_success"],
                "last_attempt": snap["last_attempt"],
                "last_error": snap["last_error"],
            }, sort_keys=True).encode("utf-8") + b"\n"
            self._send_bytes(HTTPStatus.OK if healthy else HTTPStatus.SERVICE_UNAVAILABLE, "application/json", body)
            return

        if self.path == "/snapshot.json":
            if not snap["has_sample"]:
                self._send_bytes(HTTPStatus.NOT_FOUND, "application/json", b'{"ok":false,"error":"no sample collected"}\n')
                return
            body = json.dumps(snap["payload"], sort_keys=True).encode("utf-8") + b"\n"
            self._send_bytes(HTTPStatus.OK, "application/json", body)
            return

        self._send_bytes(HTTPStatus.NOT_FOUND, "text/plain; charset=utf-8", b"not found\n")

    def log_message(self, fmt: str, *args: Any) -> None:
        sys.stderr.write("%s - - [%s] %s\n" % (self.address_string(), self.log_date_time_string(), fmt % args))

    def _send_bytes(self, status: HTTPStatus, content_type: str, body: bytes) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


class IPv6ThreadingHTTPServer(ThreadingHTTPServer):
    address_family = socket.AF_INET6


def make_server(listen_address: str, state: ExporterState) -> ThreadingHTTPServer:
    host, port = parse_listen_address(listen_address)
    server_cls: type[ThreadingHTTPServer] = ThreadingHTTPServer
    if ":" in host:
        server_cls = IPv6ThreadingHTTPServer
    server = server_cls((host, port), CalabiHandler)
    server.exporter_state = state  # type: ignore[attr-defined]
    return server


def main() -> int:
    parser = argparse.ArgumentParser(description="Run the persistent Calabi Observer exporter.")
    parser.add_argument("--once", action="store_true", help="collect and publish one full snapshot, then exit")
    args = parser.parse_args()

    state = ExporterState()
    cached_full: dict[str, Any] = {}
    if args.once:
        collect_once(full=True, cached_full=cached_full, state=state)
        return 0

    cfg = read_config()
    stop_event = threading.Event()

    def handle_signal(_signum: int, _frame: Any) -> None:
        stop_event.set()

    signal.signal(signal.SIGINT, handle_signal)
    signal.signal(signal.SIGTERM, handle_signal)

    collector_thread = threading.Thread(target=collection_loop, args=(state, stop_event), daemon=True)
    collector_thread.start()

    server = make_server(cfg["listen_address"], state)
    server.timeout = 1.0
    sys.stderr.write(f"calabi exporter listening on {cfg['listen_address']}\n")
    sys.stderr.flush()
    while not stop_event.is_set():
        server.handle_request()
    server.server_close()
    collector_thread.join(timeout=5.0)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        sys.stderr.write(f"calabi exporter failed: {exc}\n")
        raise SystemExit(1)
