#!/usr/bin/python3
"""
Prometheus textfile exporter for Calabi Observer.

This is intentionally not an HTTP server. It reuses the local observer
collector and writes a single node_exporter textfile atomically.
"""

from __future__ import annotations

import argparse
import os
import socket
import sys
import tempfile
from typing import Any

import collector


DEFAULT_OUTPUT = "/var/lib/node_exporter/textfile_collector/calabi_observer.prom"


def metric_name(raw: str) -> str:
    out = []
    for ch in raw:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        else:
            out.append("_")
    return "".join(out)


def label_value(raw: Any) -> str:
    value = str(raw)
    return value.replace("\\", "\\\\").replace("\n", "\\n").replace('"', '\\"')


def labels(**items: Any) -> str:
    clean = {k: v for k, v in items.items() if v is not None}
    if not clean:
        return ""
    body = ",".join(f'{k}="{label_value(v)}"' for k, v in sorted(clean.items()))
    return "{" + body + "}"


def emit(lines: list[str], name: str, value: Any, help_text: str, metric_type: str = "gauge", **lbls: Any) -> None:
    if value is None:
        return
    safe_name = metric_name(name)
    lines.append(f"# HELP {safe_name} {help_text}")
    lines.append(f"# TYPE {safe_name} {metric_type}")
    lines.append(f"{safe_name}{labels(**lbls)} {float(value)}")


def emit_once(seen: set[str], lines: list[str], name: str, help_text: str, metric_type: str) -> None:
    safe_name = metric_name(name)
    if safe_name in seen:
        return
    seen.add(safe_name)
    lines.append(f"# HELP {safe_name} {help_text}")
    lines.append(f"# TYPE {safe_name} {metric_type}")


def emit_sample(seen: set[str], lines: list[str], name: str, value: Any, help_text: str, metric_type: str = "gauge", **lbls: Any) -> None:
    if value is None:
        return
    safe_name = metric_name(name)
    emit_once(seen, lines, safe_name, help_text, metric_type)
    lines.append(f"{safe_name}{labels(**lbls)} {float(value)}")


def format_metrics(payload: dict[str, Any]) -> str:
    lines: list[str] = [
        "# Generated by calabi-observer-prometheus",
    ]
    seen: set[str] = set()
    hostname = socket.getfqdn() or socket.gethostname()

    emit_sample(seen, lines, "calabi_observer_up", 1, "Calabi Observer exporter completed successfully.", host=hostname)
    emit_sample(seen, lines, "calabi_observer_timestamp_seconds", payload.get("timestamp"), "Unix timestamp of the collected observer sample.", host=hostname)

    mem = payload.get("meminfo") or {}
    for key, value in mem.items():
        emit_sample(seen, lines, f"calabi_memory_{key.lower()}_bytes", value, f"/proc/meminfo {key} in bytes.", host=hostname)
    emit_sample(seen, lines, "calabi_guest_memory_committed_bytes", payload.get("guest_memory_bytes"), "Total configured guest memory in bytes.", host=hostname)
    emit_sample(seen, lines, "calabi_guest_vcpus", payload.get("guest_vcpus"), "Total configured guest vCPUs.", host=hostname)

    ksm = payload.get("ksm") or {}
    for key, value in ksm.items():
        metric = f"calabi_ksm_{key}"
        help_text = f"KSM {key} from /sys/kernel/mm/ksm."
        emit_sample(seen, lines, metric, value, help_text, host=hostname)

    thp = payload.get("thp") or {}
    emit_sample(seen, lines, "calabi_thp_enabled", 1 if thp.get("enabled") and thp.get("enabled") != "never" else 0, "Transparent hugepage enabled state as a boolean gauge.", host=hostname, mode=thp.get("enabled"))

    for entry in payload.get("zram") or []:
        device = entry.get("name")
        algorithm = entry.get("algorithm")
        for key in [
            "disksize_bytes", "data_bytes", "compressed_bytes", "total_bytes",
            "mem_used_bytes", "mem_used_peak_bytes", "estimated_saved_bytes",
            "writeback_limit_bytes",
        ]:
            emit_sample(seen, lines, f"calabi_zram_{key}", entry.get(key), f"zram {key}.", host=hostname, device=device, algorithm=algorithm)
        emit_sample(seen, lines, "calabi_zram_writeback_attached", 1 if entry.get("backing_dev") else 0, "Whether zram has a writeback backing device attached.", host=hostname, device=device, backing_dev=entry.get("backing_dev"))
        emit_sample(seen, lines, "calabi_zram_writeback_limit_enabled", 1 if entry.get("writeback_limit_enabled") else 0, "Whether zram writeback limit enforcement is enabled.", host=hostname, device=device)
        for key, value in (entry.get("mm_stat") or {}).items():
            emit_sample(seen, lines, f"calabi_zram_mm_{key}", value, f"zram mm_stat {key}.", host=hostname, device=device)
        for key, value in (entry.get("io_stat") or {}).items():
            emit_sample(seen, lines, f"calabi_zram_io_{key}", value, f"zram io_stat {key}.", host=hostname, device=device)
        for key, value in (entry.get("bd_stat") or {}).items():
            if key == "page_size":
                continue
            emit_sample(seen, lines, f"calabi_zram_writeback_{key}", value, f"zram bd_stat {key}.", host=hostname, device=device)

    for swap in payload.get("swap") or []:
        emit_sample(seen, lines, "calabi_swap_size_bytes", swap.get("size_bytes"), "Swap device size in bytes.", host=hostname, device=swap.get("name"))
        emit_sample(seen, lines, "calabi_swap_used_bytes", swap.get("used_bytes"), "Swap device used bytes.", host=hostname, device=swap.get("name"))
        emit_sample(seen, lines, "calabi_swap_priority", swap.get("priority"), "Swap device priority.", host=hostname, device=swap.get("name"))

    for key, value in (payload.get("vmstat_swap") or {}).items():
        emit_sample(seen, lines, f"calabi_vmstat_{key}", value, f"/proc/vmstat {key}.", "counter", host=hostname)

    for tier, entry in (payload.get("tier_cgroups") or {}).items():
        emit_sample(seen, lines, "calabi_tier_cpu_weight", entry.get("cpu_weight"), "cgroup v2 cpu.weight for a Calabi tier.", host=hostname, tier=tier)
        for key, value in (entry.get("cpu_stat") or {}).items():
            metric_type = "counter" if key in {"usage_usec", "user_usec", "system_usec", "nr_periods", "nr_throttled", "throttled_usec"} else "gauge"
            emit_sample(seen, lines, f"calabi_tier_cpu_{key}", value, f"cgroup v2 cpu.stat {key} for a Calabi tier.", metric_type, host=hostname, tier=tier)

    for domain in payload.get("domains") or []:
        emit_sample(seen, lines, "calabi_domain_memory_bytes", domain.get("memory_bytes"), "Configured libvirt domain memory in bytes.", host=hostname, domain=domain.get("name"), tier=domain.get("tier"))
        emit_sample(seen, lines, "calabi_domain_vcpus", domain.get("vcpus"), "Configured libvirt domain vCPUs.", host=hostname, domain=domain.get("name"), tier=domain.get("tier"))

    for domain, stat in (payload.get("domain_cgroups") or {}).items():
        if not stat:
            continue
        for key, value in stat.items():
            metric_type = "counter" if key in {"usage_usec", "user_usec", "system_usec", "nr_periods", "nr_throttled", "throttled_usec"} else "gauge"
            emit_sample(seen, lines, f"calabi_domain_cpu_{key}", value, f"cgroup v2 cpu.stat {key} for a libvirt domain.", metric_type, host=hostname, domain=domain)

    # Host CPU aggregate
    host_cpu = payload.get("host_cpu") or {}
    agg = host_cpu.get("aggregate") or {}
    for key in ("user", "nice", "system", "idle", "iowait", "irq", "softirq", "steal"):
        emit_sample(seen, lines, f"calabi_host_cpu_{key}_ticks", agg.get(key), f"Aggregate /proc/stat {key} jiffies.", "counter", host=hostname)

    # Per-CPU utilization
    per_cpu = host_cpu.get("per_cpu") or {}
    for cpu_id, cpu_stat in per_cpu.items():
        for key in ("user", "nice", "system", "idle", "iowait", "irq", "softirq", "steal"):
            emit_sample(seen, lines, f"calabi_cpu_{key}_ticks", cpu_stat.get(key), f"Per-CPU /proc/stat {key} jiffies.", "counter", host=hostname, cpu=cpu_id)

    # Per-CPU frequency
    cpu_freq = payload.get("cpu_freq") or {}
    for cpu_id, mhz in cpu_freq.items():
        emit_sample(seen, lines, "calabi_cpu_frequency_mhz", mhz, "Current CPU frequency in MHz from /proc/cpuinfo.", host=hostname, cpu=cpu_id)

    emit_sample(seen, lines, "calabi_host_cpu_count", payload.get("num_cpus"), "Total logical CPU count.", host=hostname)

    # Kernel thread CPU accounting
    for thread_name, thread_stat in (payload.get("kernel_threads") or {}).items():
        if not thread_stat:
            continue
        emit_sample(seen, lines, "calabi_kernel_thread_cpu_seconds", thread_stat.get("total_seconds"), "Cumulative CPU seconds for a kernel memory-management thread.", "counter", host=hostname, thread=thread_name)

    # CPU pool assignments
    cpu_pools = payload.get("cpu_pools") or {}
    for pool_name, cpu_range in cpu_pools.items():
        if not cpu_range:
            continue
        count = sum(1 for _ in cpu_range.split(",") for _ in [None]) if cpu_range else 0
        expanded = []
        for part in cpu_range.split(","):
            if "-" in part:
                s, e = part.split("-", 1)
                expanded.extend(range(int(s), int(e) + 1))
            else:
                expanded.append(int(part))
        emit_sample(seen, lines, "calabi_cpu_pool_size", len(expanded), "Number of logical CPUs assigned to a CPU pool.", host=hostname, pool=pool_name)

    # Tier totals
    for tier, totals in (payload.get("tier_totals") or {}).items():
        emit_sample(seen, lines, "calabi_tier_domain_count", totals.get("domains"), "Number of running domains in a Calabi tier.", host=hostname, tier=tier)
        emit_sample(seen, lines, "calabi_tier_memory_committed_bytes", totals.get("memory_bytes"), "Total configured memory for domains in a Calabi tier.", host=hostname, tier=tier)
        emit_sample(seen, lines, "calabi_tier_vcpus", totals.get("vcpus"), "Total configured vCPUs for domains in a Calabi tier.", host=hostname, tier=tier)

    # Aggregate zram and swap summaries
    emit_sample(seen, lines, "calabi_zram_estimated_saved_bytes_total", payload.get("zram_estimated_saved_bytes"), "Aggregate estimated RAM saved by zram compression.", host=hostname)
    emit_sample(seen, lines, "calabi_swap_used_bytes_total", payload.get("swap_used_bytes"), "Aggregate swap bytes used across all devices.", host=hostname)

    for entry in payload.get("domain_ksm") or []:
        emit_sample(seen, lines, "calabi_domain_ksm_profit_bytes", entry.get("profit_bytes"), "KSM memory profit attributed to a libvirt domain process.", host=hostname, domain=entry.get("name"), tier=entry.get("tier"))
        emit_sample(seen, lines, "calabi_domain_ksm_dependency_ratio", entry.get("dependency_ratio"), "Domain KSM profit divided by configured guest memory.", host=hostname, domain=entry.get("name"), tier=entry.get("tier"))
        emit_sample(seen, lines, "calabi_domain_ksm_merge_density", entry.get("merge_density"), "Domain KSM merging pages divided by mergeable reverse-map items.", host=hostname, domain=entry.get("name"), tier=entry.get("tier"))

    for entry in payload.get("domain_swap") or []:
        emit_sample(seen, lines, "calabi_domain_swap_bytes", entry.get("swap_bytes"), "Swap attributed to a libvirt domain process.", host=hostname, domain=entry.get("name"), tier=entry.get("tier"))
        emit_sample(seen, lines, "calabi_domain_swap_dependency_ratio", entry.get("dependency_ratio"), "Domain swap divided by configured guest memory.", host=hostname, domain=entry.get("name"), tier=entry.get("tier"))

    return "\n".join(lines) + "\n"


def collect_metrics() -> str:
    return format_metrics(collector.collect(fast=False))


def write_atomic(path: str, content: str) -> None:
    directory = os.path.dirname(path)
    os.makedirs(directory, mode=0o755, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".calabi_observer.", suffix=".prom", dir=directory, text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
            fh.flush()
            os.fsync(fh.fileno())
        os.chmod(tmp_path, 0o644)
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except FileNotFoundError:
            pass
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description="Export Calabi Observer metrics in Prometheus textfile format.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    write_atomic(args.output, collect_metrics())
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        sys.stderr.write(f"calabi observer prometheus export failed: {exc}\n")
        raise SystemExit(1)
