---
- name: Validate local OpenShift cluster status from the hypervisor boundary
  hosts: hypervisors
  gather_facts: true
  vars_files:
    - ../../vars/global/execution_environment.yml
    - ../../vars/cluster/openshift_installer_binaries.yml
    - ../../vars/cluster/openshift_install_cluster.yml
    - ../../vars/cluster/openshift_agent_media.yml
    - ../../vars/guests/openshift_cluster_vm.yml
  roles:
    - role: openshift_post_install_validate
