---
- import_playbook: cluster/openshift-installer-binaries.yml
  tags:
    - installer-binaries
    - cluster-prep
- import_playbook: cluster/openshift-install-artifacts.yml
  tags:
    - install-artifacts
    - cluster-prep
- import_playbook: cluster/openshift-agent-media.yml
  tags:
    - agent-media
    - cluster-prep
- import_playbook: cluster/openshift-cluster.yml
  tags:
    - cluster-vms
    - cluster-build
- import_playbook: cluster/openshift-cluster-verify.yml
  tags:
    - cluster-verify
    - cluster-build
- import_playbook: cluster/openshift-pivot-wait.yml
  tags:
    - pivot-wait
    - cluster-build
- import_playbook: maintenance/detach-install-media.yml
  tags:
    - detach-install-media
    - cluster-finish
- import_playbook: cluster/openshift-install-wait.yml
  tags:
    - bootstrap-wait
    - cluster-finish
- import_playbook: cluster/openshift-install-complete.yml
  tags:
    - install-complete
    - cluster-finish
- import_playbook: day2/openshift-post-install-validate.yml
  tags:
    - day2-validate
    - cluster-finish
